### ISSUE TITLE
Forge Recipes

### ISSUE THREAD

**Issue by 3alampro** [scaling-laravel/forge.scalinglaravel.com#1]
Hello,

can you kindly share all Forge Recipes on this course 

https://serversforhackers.com/scaling-laravel/forge/forge-recipes

I'm waiting for the lunch day to purchase it hopefully soon

**Comment by fideloper** [comment]
I've added them to the appropriate video page! https://serversforhackers.com/scaling-laravel/forge/forge-recipes

Thanks

**Comment by fideloper** [comment]
Here you go!
